before_script:
  - curl -s https://www.parse.com/downloads/cloud_code/installer.sh | sudo /bin/bash

stages:
  #- build
  #- test
  - deploy

before_script:
  - /bin/echo "${ACCOUNT_KEY}" | /usr/local/bin/parse configure accountkey -d

#job_1
# script:
#   - <SCRIPT TO BUILD SOMETHING>
# stage: build
#
#job_2
# script:
#   - <SCRIPT TO TEST SOMETHING>
# stage: test

job_3:
  script:
    - /usr/local/bin/parse deploy -f
  stage: deploy
  only: development
